name: DogeWorld
version: 0.4
author: Sarah Klocke (@SarahIsWeird)
main: com.sarahisweird.dogeworld.DogeWorld
api-version: 1.16

commands:
  rtp:
    usage: "Usage: /rtp"
    description: "Teleports you to a random location in the world."
  spawn:
    usage: "Usage: /spawn"
    description: "Teleports you back to the spawn point."
  heal:
    usage: "Usage: /heal"
    description: "Heals and feeds you."
  fly:
    usage: "Usage: /fly"
    description: "Allows you to fly in survival mode."
  db:
    usage: "Usage: /db §osubcommand§r"
    description: "Provides access to the SQLite database."
  colors:
    usage: "Usage: /colors"
    description: "Displays all available color codes."
  rank:
    usage: "Usage: /rank §osubcommand§r"
    description: "Provides an in-game interface for rank manipulation."
  nick:
    usage: "Usage: /nick [player] <nickname>"
    description: "Allows you to set a custom name."